#!/bin/bash -x
# Source: https://github.com/rrwhx/runspec
DIR26=$(realpath .)
cd ${DIR26}/benchspec/CPU/706.stockfish_r/run/run_base_train_${EXT26}.0000 &&  ./stockfish_base.${EXT26} bench 1600 1 24 spec_train.fen depth nnue  1>stockfish_spec_train_nnue.out 2>stockfish_spec_train_nnue.err
cd ${DIR26}/benchspec/CPU/706.stockfish_r/run/run_base_train_${EXT26}.0000 &&  ./stockfish_base.${EXT26} bench 1600 1 24 spec_train.fen depth classical  1>stockfish_spec_train_classical.out 2>stockfish_spec_train_classical.err
cd ${DIR26}/benchspec/CPU/707.ntest_r/run/run_base_train_${EXT26}.0000 &&  ./ntest_r_base.${EXT26} Othello.60e4.ggf 19 19  1>ntest.Othello.60e4.19.19.out 2>ntest.Othello.60e4.19.19.err
cd ${DIR26}/benchspec/CPU/708.sqlite_r/run/run_base_train_${EXT26}.0000 &&  ./sqlite_r_base.${EXT26} --memdb --size 500 --testset main --verify  1>sqlite_r.main.out 2>sqlite_r.main.err
cd ${DIR26}/benchspec/CPU/708.sqlite_r/run/run_base_train_${EXT26}.0000 &&  ./sqlite_r_base.${EXT26} --memdb --size 500 --testset cte --verify  1>sqlite_r.cte.out 2>sqlite_r.cte.err
cd ${DIR26}/benchspec/CPU/710.omnetpp_r/run/run_base_train_${EXT26}.0000 &&  ./omnetpp_r_base.${EXT26} -f randomMesh.ini -c General  1>omnetpp.General-0.out 2>omnetpp.General-0.err
cd ${DIR26}/benchspec/CPU/710.omnetpp_r/run/run_base_train_${EXT26}.0000 &&  ./omnetpp_r_base.${EXT26} -f queuenet.ini -c OneFifo  1>omnetpp.OneFifo-0.out 2>omnetpp.OneFifo-0.err
cd ${DIR26}/benchspec/CPU/714.cpython_r/run/run_base_train_${EXT26}.0000 &&  ./cpython_r_base.${EXT26} -I -B coreml_pb.py -i 10 -a -c -m PoseNetMobileNet100S16FP16.mlmodel  1>cpython_r_0.out 2>cpython_r_0.err
cd ${DIR26}/benchspec/CPU/714.cpython_r/run/run_base_train_${EXT26}.0000 &&  ./cpython_r_base.${EXT26} -I -B dna_bench.py 200000  1>cpython_r_1.out 2>cpython_r_1.err
cd ${DIR26}/benchspec/CPU/721.gcc_r/run/run_base_train_${EXT26}.0000 &&  ./cc1_r_base.${EXT26} 200.c -O2 -o 200.c.opts-O2.s  1>200.c.opts-O2.out 2>200.c.opts-O2.err
cd ${DIR26}/benchspec/CPU/721.gcc_r/run/run_base_train_${EXT26}.0000 &&  ./cc1_r_base.${EXT26} scilab.c -O3 -o scilab.c.opts-O3.s  1>scilab.c.opts-O3.out 2>scilab.c.opts-O3.err
cd ${DIR26}/benchspec/CPU/721.gcc_r/run/run_base_train_${EXT26}.0000 &&  ./cc1_r_base.${EXT26} train01.c -O3 -finline-limit=50000 -o train01.c.opts-O3_-finline-limit_50000.s  1>train01.c.opts-O3_-finline-limit_50000.out 2>train01.c.opts-O3_-finline-limit_50000.err
cd ${DIR26}/benchspec/CPU/723.llvm_r/run/run_base_train_${EXT26}.0000 &&  ./llvm-opt_r_base.${EXT26} train.ll -S -O3 -mcpu=pwr9 --sha512 -o train.ll.opts-S_-O3_-mcpu_pwr9.ll  1>train.ll.opts-S_-O3_-mcpu_pwr9.out 2>train.ll.opts-S_-O3_-mcpu_pwr9.err
cd ${DIR26}/benchspec/CPU/723.llvm_r/run/run_base_train_${EXT26}.0000 &&  ./llvm-opt_r_base.${EXT26} ELFObject.ll -S -O2 -inline-threshold=50000 -mcpu=pwr9 --sha512 -o ELFObject.ll.opts-S_-O2_-inline-threshold_50000_-mcpu_pwr9.ll  1>ELFObject.ll.opts-S_-O2_-inline-threshold_50000_-mcpu_pwr9.out 2>ELFObject.ll.opts-S_-O2_-inline-threshold_50000_-mcpu_pwr9.err
cd ${DIR26}/benchspec/CPU/727.cppcheck_r/run/run_base_train_${EXT26}.0000 &&  ./cppcheck_r_base.${EXT26} --force lua-5.4.7/lcode.c --enable=all --checkers-report=lcode_report.txt --output-file=lcode_bogey.txt --suppress=missingIncludeSystem --platform=unix64  1>cppcheck_r.lcode_bogey.out 2>cppcheck_r.lcode_bogey.err
cd ${DIR26}/benchspec/CPU/727.cppcheck_r/run/run_base_train_${EXT26}.0000 &&  ./cppcheck_r_base.${EXT26} --force automaticMeshSizeField.cpp meshGRegionBoundaryLayer.cpp meshGRegionLocalMeshMod.cpp --enable=all --checkers-report=mesh_report.txt --output-file=mesh_bogey.txt --enable=all --suppress=missingIncludeSystem --suppress=missingInclude --check-level=exhaustive --platform=unix64  1>cppcheck_r.mesh_bogey.out 2>cppcheck_r.mesh_bogey.err
cd ${DIR26}/benchspec/CPU/729.abc_r/run/run_base_train_${EXT26}.0000 &&  ./abc_r_base.${EXT26} -F ucsb_152.in  1>ucsb_152.out 2>ucsb_152.err
cd ${DIR26}/benchspec/CPU/729.abc_r/run/run_base_train_${EXT26}.0000 &&  ./abc_r_base.${EXT26} -F des_perf.in  1>des_perf.out 2>des_perf.err
cd ${DIR26}/benchspec/CPU/729.abc_r/run/run_base_train_${EXT26}.0000 &&  ./abc_r_base.${EXT26} -F sparcT1_core.in  1>sparcT1_core.out 2>sparcT1_core.err
cd ${DIR26}/benchspec/CPU/734.vpr_r/run/run_base_train_${EXT26}.0000 &&  ./vpr_base.${EXT26} stratixiv_arch.timing.xml sudoku_check_stratixiv_arch_timing.blif --place_algorithm bounding_box --RL_agent_placement off --max_criticality 0.0 --init_t 512 --alpha_t 0.75 --exit_t 1 --router_initial_timing all_critical --routing_failure_predictor off --route_chan_width 300 --max_router_iterations 20 --router_lookahead classic --initial_pres_fac 1.0 --pres_fac_mult 2.0 --astar_fac 1.5 --router_profiler_astar_fac 1.5 --seed 3 --sdc_file sudoku_check_stratixiv_arch_timing.sdc --pack_verbosity 0 --netlist_verbosity 0 --base_cost_type demand_only --inner_num 4 --read_initial_place_file ref_sudoku_check_stratixiv_arch_timing.init.place --place  1>sudoku_check_stratixiv_arch_timing.blif.place.out 2>sudoku_check_stratixiv_arch_timing.blif.place.err
cd ${DIR26}/benchspec/CPU/734.vpr_r/run/run_base_train_${EXT26}.0000 &&  ./vpr_base.${EXT26} stratixiv_arch.timing.xml sudoku_check_stratixiv_arch_timing.blif --place_algorithm bounding_box --place_static_notiming_move_prob 50 25 25 --max_criticality 0.0 --router_initial_timing all_critical --routing_failure_predictor off --route_chan_width 300 --max_router_iterations 20 --router_lookahead classic --initial_pres_fac 1.0 --pres_fac_mult 2.0 --astar_fac 1.5 --router_profiler_astar_fac 1.5 --seed 3 --sdc_file sudoku_check_stratixiv_arch_timing.sdc --pack_verbosity 0 --netlist_verbosity 0 --base_cost_type demand_only --place_file ref_sudoku_check_stratixiv_arch_timing.place --analysis --route  1>sudoku_check_stratixiv_arch_timing.blif.route.out 2>sudoku_check_stratixiv_arch_timing.blif.route.err
cd ${DIR26}/benchspec/CPU/735.gem5_r/run/run_base_train_${EXT26}.0000 &&  ./gem5sim_base.${EXT26} --stats-file=synthetic_traffic.py_LinearGenerator_100.stats.txt synthetic_traffic.py LinearGenerator 100  1>synthetic_traffic.py_LinearGenerator_100.out 2>synthetic_traffic.py_LinearGenerator_100.err
cd ${DIR26}/benchspec/CPU/750.sealcrypto_r/run/run_base_train_${EXT26}.0000 &&  ./sealcrypto_r_base.${EXT26} train australia_state_capitals_train.csv Victoria  1>homoencrypt.train_australia_state_capitals_train.csv_Victoria.out 2>homoencrypt.train_australia_state_capitals_train.csv_Victoria.err
cd ${DIR26}/benchspec/CPU/753.ns3_r/run/run_base_train_${EXT26}.0000 &&  ./ns3_r_base.${EXT26} wifi-mixed-network --isUdp=0 --simulationTime=10 --RngSeed=1 --RngRun=1  1>wifi-mixed-network_0.out 2>wifi-mixed-network_0.err
cd ${DIR26}/benchspec/CPU/753.ns3_r/run/run_base_train_${EXT26}.0000 &&  ./ns3_r_base.${EXT26} wifi-mixed-network --isUdp=1 --simulationTime=10 --payloadSize=2048 --RngSeed=1 --RngRun=1  1>wifi-mixed-network_1.out 2>wifi-mixed-network_1.err
cd ${DIR26}/benchspec/CPU/777.zstd_r/run/run_base_train_${EXT26}.0000 &&  ./zstd_base.${EXT26} -b3 -e12 --verbose -i15  1>zstd.b3_e12_verbose_i15.out 2>zstd.b3_e12_verbose_i15.err
cd ${DIR26}/benchspec/CPU/709.cactus_r/run/run_base_train_${EXT26}.0000 &&  ./cactus_base.${EXT26} ShiftedGaugeWave.par  1>cactus.out 2>cactus.err
cd ${DIR26}/benchspec/CPU/722.palm_r/run/run_base_train_${EXT26}.0000 &&  ./palm_r_base.${EXT26} <runfile_atmos 1>palm_r.out 2>palm_r.err
cd ${DIR26}/benchspec/CPU/731.astcenc_r/run/run_base_train_${EXT26}.0000 &&  ./astcenc_r_base.${EXT26} train-inputs.txt  1>astcenc_r.0.out 2>astcenc_r.0.err
cd ${DIR26}/benchspec/CPU/736.ocio_r/run/run_base_train_${EXT26}.0000 &&  ./ocioperf_base.${EXT26} --spec-validation-offset 20 --spec-validation-stride 3 --spec-validation-pixels 128 --bitdepths ui16 f32 --iter 99 --test 0 --transform ctf/metadata.ctf  1>perf_metadata.ctf.out 2>perf_metadata.ctf.err
cd ${DIR26}/benchspec/CPU/736.ocio_r/run/run_base_train_${EXT26}.0000 &&  ./ocioperf_base.${EXT26} --spec-validation-offset 30 --spec-validation-stride 5 --spec-validation-pixels 129 --bitdepths f32 f32 --iter 30 --test 0 --transform clf/aces_to_video_with_look.clf  1>perf_aces_to_video_with_look.clf.out 2>perf_aces_to_video_with_look.clf.err
cd ${DIR26}/benchspec/CPU/736.ocio_r/run/run_base_train_${EXT26}.0000 &&  ./ocioperf_base.${EXT26} --spec-validation-offset 40 --spec-validation-stride 7 --spec-validation-pixels 130 --bitdepths ui16 ui16 --iter 22 --8kres --test -1 --transform clf/lut1d_long.clf  1>perf_lut1d_long.clf.out 2>perf_lut1d_long.clf.err
cd ${DIR26}/benchspec/CPU/736.ocio_r/run/run_base_train_${EXT26}.0000 &&  ./ocioperf_base.${EXT26} --spec-validation-offset 50 --spec-validation-stride 9 --spec-validation-pixels 131 --bitdepths ui16 ui16 --iter 2 --8kres --test -1 --transform clf/heavy_transform.clf  1>perf_heavy_transform.clf.out 2>perf_heavy_transform.clf.err
cd ${DIR26}/benchspec/CPU/737.gmsh_r/run/run_base_train_${EXT26}.0000 &&  ./gmsh_r_base.${EXT26} -option gmsh.opts -nt 0 sphere-discrete.geo  1>sphere-discrete.geo.out 2>sphere-discrete.geo.err
cd ${DIR26}/benchspec/CPU/737.gmsh_r/run/run_base_train_${EXT26}.0000 &&  ./gmsh_r_base.${EXT26} -option gmsh.opts -nt 0 spec.geo -smooth 2 -clscale .27  1>spec.geo.out 2>spec.geo.err
cd ${DIR26}/benchspec/CPU/748.flightdm_r/run/run_base_train_${EXT26}.0000 &&  ./JSBSim_base.${EXT26} --nohighlight scripts/weather-balloon.xml  1>weather-balloon.xml.out 2>weather-balloon.xml.err
cd ${DIR26}/benchspec/CPU/748.flightdm_r/run/run_base_train_${EXT26}.0000 &&  ./JSBSim_base.${EXT26} --nohighlight scripts/f16_test.xml  1>f16_test.xml.out 2>f16_test.xml.err
cd ${DIR26}/benchspec/CPU/748.flightdm_r/run/run_base_train_${EXT26}.0000 &&  ./JSBSim_base.${EXT26} --nohighlight scripts/c3105.xml  1>c3105.xml.out 2>c3105.xml.err
cd ${DIR26}/benchspec/CPU/748.flightdm_r/run/run_base_train_${EXT26}.0000 &&  ./JSBSim_base.${EXT26} --nohighlight scripts/Short_S23_2.xml  1>Short_S23_2.xml.out 2>Short_S23_2.xml.err
cd ${DIR26}/benchspec/CPU/749.fotonik3d_r/run/run_base_train_${EXT26}.0000 &&  ./fotonik3d_r_base.${EXT26}  1>fotonik3d.log 2>fotonik3d.err
cd ${DIR26}/benchspec/CPU/765.roms_r/run/run_base_train_${EXT26}.0000 &&  ./roms_r_base.${EXT26} <roms_benchmark1.in.x 1>roms_benchmark1.log 2>roms_benchmark1.err
cd ${DIR26}/benchspec/CPU/766.femflow_r/run/run_base_train_${EXT26}.0000 &&  ./femflow_r_base.${EXT26} train.prm  1>femflow.out 2>femflow.err
cd ${DIR26}/benchspec/CPU/767.nest_r/run/run_base_train_${EXT26}.0000 &&  ./nest_r_base.${EXT26} balancedneuron-2.sli  1>balancedneuron-2.sli.out 2>balancedneuron-2.sli.err
cd ${DIR26}/benchspec/CPU/767.nest_r/run/run_base_train_${EXT26}.0000 &&  ./nest_r_base.${EXT26} cuba_ps.sli  1>cuba_ps.sli.out 2>cuba_ps.sli.err
cd ${DIR26}/benchspec/CPU/767.nest_r/run/run_base_train_${EXT26}.0000 &&  ./nest_r_base.${EXT26} cuba.sli  1>cuba.sli.out 2>cuba.sli.err
cd ${DIR26}/benchspec/CPU/772.marian_r/run/run_base_train_${EXT26}.0000 &&  ./marian-decoder_base.${EXT26} --cpu-threads 1 -m model.alphas.npz -v vocab.spm vocab.spm --beam-size 2 --mini-batch 32 --maxi-batch 100 --maxi-batch-sort src -w 64 --skip-cost --gemm-type intgemm8 --intgemm-options precomputed-alpha standard-only --quiet --quiet-translation -i technology_and_courage.en --log technology_and_courage.log --log-level off -o technology_and_courage.out  1>run_technology_and_courage.out.out 2>run_technology_and_courage.out.err
cd ${DIR26}/benchspec/CPU/782.lbm_r/run/run_base_train_${EXT26}.0000 &&  ./lbm_r_base.${EXT26} 120 reference.dat 0 0 200_200_130_ldc.of  1>lbm.out 2>lbm.err
