#!/bin/bash -x
# Source: https://github.com/rrwhx/runspec
DIR26=$(realpath .)
cd ${DIR26}/benchspec/CPU/706.stockfish_r/run/run_base_refrate_${EXT26}.0000 &&  ./stockfish_base.${EXT26} bench 1600 1 26 spec_ref_pos_1to6.fen depth classical  1>stockfish_spec_ref_pos_1to6_classical.out 2>stockfish_spec_ref_pos_1to6_classical.err
cd ${DIR26}/benchspec/CPU/706.stockfish_r/run/run_base_refrate_${EXT26}.0000 &&  ./stockfish_base.${EXT26} bench 1600 1 26 spec_ref_pos_1to6.fen depth nnue  1>stockfish_spec_ref_pos_1to6_nnue.out 2>stockfish_spec_ref_pos_1to6_nnue.err
cd ${DIR26}/benchspec/CPU/706.stockfish_r/run/run_base_refrate_${EXT26}.0000 &&  ./stockfish_base.${EXT26} bench 1600 1 26 spec_ref_pos_7to11.fen depth nnue  1>stockfish_spec_ref_pos_7to11_nnue.out 2>stockfish_spec_ref_pos_7to11_nnue.err
cd ${DIR26}/benchspec/CPU/707.ntest_r/run/run_base_refrate_${EXT26}.0000 &&  ./ntest_r_base.${EXT26} Othello.154.ggf 20 16  1>ntest.Othello.154.20.16.out 2>ntest.Othello.154.20.16.err
cd ${DIR26}/benchspec/CPU/708.sqlite_r/run/run_base_refrate_${EXT26}.0000 &&  ./sqlite_r_base.${EXT26} --memdb --size 2000 --testset main --verify  1>sqlite_r.main.out 2>sqlite_r.main.err
cd ${DIR26}/benchspec/CPU/708.sqlite_r/run/run_base_refrate_${EXT26}.0000 &&  ./sqlite_r_base.${EXT26} --memdb --size 2000 --testset cte --verify  1>sqlite_r.cte.out 2>sqlite_r.cte.err
cd ${DIR26}/benchspec/CPU/708.sqlite_r/run/run_base_refrate_${EXT26}.0000 &&  ./sqlite_r_base.${EXT26} --memdb --size 1000 --testset fp --verify  1>sqlite_r.fp.out 2>sqlite_r.fp.err
cd ${DIR26}/benchspec/CPU/710.omnetpp_r/run/run_base_refrate_${EXT26}.0000 &&  ./omnetpp_r_base.${EXT26} -f randomMesh.ini -c General  1>omnetpp.General-0.out 2>omnetpp.General-0.err
cd ${DIR26}/benchspec/CPU/710.omnetpp_r/run/run_base_refrate_${EXT26}.0000 &&  ./omnetpp_r_base.${EXT26} -f queuenet.ini -c OneFifo  1>omnetpp.OneFifo-0.out 2>omnetpp.OneFifo-0.err
cd ${DIR26}/benchspec/CPU/710.omnetpp_r/run/run_base_refrate_${EXT26}.0000 &&  ./omnetpp_r_base.${EXT26} -f queuenet.ini -c TandemFifos  1>omnetpp.TandemFifos-0.out 2>omnetpp.TandemFifos-0.err
cd ${DIR26}/benchspec/CPU/710.omnetpp_r/run/run_base_refrate_${EXT26}.0000 &&  ./omnetpp_r_base.${EXT26} -f queuenet.ini -c SmallCQN  1>omnetpp.SmallCQN-0.out 2>omnetpp.SmallCQN-0.err
cd ${DIR26}/benchspec/CPU/710.omnetpp_r/run/run_base_refrate_${EXT26}.0000 &&  ./omnetpp_r_base.${EXT26} -f queuenet.ini -c Ring  1>omnetpp.Ring-0.out 2>omnetpp.Ring-0.err
cd ${DIR26}/benchspec/CPU/710.omnetpp_r/run/run_base_refrate_${EXT26}.0000 &&  ./omnetpp_r_base.${EXT26} -f queuenet.ini -c Terminal  1>omnetpp.Terminal-0.out 2>omnetpp.Terminal-0.err
cd ${DIR26}/benchspec/CPU/710.omnetpp_r/run/run_base_refrate_${EXT26}.0000 &&  ./omnetpp_r_base.${EXT26} -f queuenet.ini -c CallCenter  1>omnetpp.CallCenter-0.out 2>omnetpp.CallCenter-0.err
cd ${DIR26}/benchspec/CPU/710.omnetpp_r/run/run_base_refrate_${EXT26}.0000 &&  ./omnetpp_r_base.${EXT26} -f queuenet.ini -c ForkJoin  1>omnetpp.ForkJoin-0.out 2>omnetpp.ForkJoin-0.err
cd ${DIR26}/benchspec/CPU/710.omnetpp_r/run/run_base_refrate_${EXT26}.0000 &&  ./omnetpp_r_base.${EXT26} -f queuenet.ini -c ResourceAllocation  1>omnetpp.ResourceAllocation-0.out 2>omnetpp.ResourceAllocation-0.err
cd ${DIR26}/benchspec/CPU/710.omnetpp_r/run/run_base_refrate_${EXT26}.0000 &&  ./omnetpp_r_base.${EXT26} -f queuenet.ini -c AllocDealloc  1>omnetpp.AllocDealloc-0.out 2>omnetpp.AllocDealloc-0.err
cd ${DIR26}/benchspec/CPU/714.cpython_r/run/run_base_refrate_${EXT26}.0000 &&  ./cpython_r_base.${EXT26} -I -B coreml_pb.py -i 2 -a -m Resnet50Headless.mlmodel -d 10  1>cpython_r_0.out 2>cpython_r_0.err
cd ${DIR26}/benchspec/CPU/714.cpython_r/run/run_base_refrate_${EXT26}.0000 &&  ./cpython_r_base.${EXT26} -I -B coreml_pb.py -i 5 -a -c -m MobileNetV2.mlmodel -d 20  1>cpython_r_1.out 2>cpython_r_1.err
cd ${DIR26}/benchspec/CPU/714.cpython_r/run/run_base_refrate_${EXT26}.0000 &&  ./cpython_r_base.${EXT26} -I -B dna_bench.py 600000  1>cpython_r_2.out 2>cpython_r_2.err
cd ${DIR26}/benchspec/CPU/721.gcc_r/run/run_base_refrate_${EXT26}.0000 &&  ./cc1_r_base.${EXT26} gcc-pp.c -O2 -fpic -o gcc-pp.c.opts-O2_-fpic.s  1>gcc-pp.c.opts-O2_-fpic.out 2>gcc-pp.c.opts-O2_-fpic.err
cd ${DIR26}/benchspec/CPU/721.gcc_r/run/run_base_refrate_${EXT26}.0000 &&  ./cc1_r_base.${EXT26} gcc-smaller.c -O3 -fipa-pta -o gcc-smaller.c.opts-O3_-fipa-pta.s  1>gcc-smaller.c.opts-O3_-fipa-pta.out 2>gcc-smaller.c.opts-O3_-fipa-pta.err
cd ${DIR26}/benchspec/CPU/721.gcc_r/run/run_base_refrate_${EXT26}.0000 &&  ./cc1_r_base.${EXT26} ref32.c -O3 -finline-limit=12000 -fno-tree-vrp -o ref32.c.opts-O3_-finline-limit_12000_-fno-tree-vrp.s  1>ref32.c.opts-O3_-finline-limit_12000_-fno-tree-vrp.out 2>ref32.c.opts-O3_-finline-limit_12000_-fno-tree-vrp.err
cd ${DIR26}/benchspec/CPU/723.llvm_r/run/run_base_refrate_${EXT26}.0000 &&  ./llvm-opt_r_base.${EXT26} transformsplus.bc -S -O3 -mcpu=pwr9 --sha512 -o transformsplus.bc.opts-S_-O3_-mcpu_pwr9.ll  1>transformsplus.bc.opts-S_-O3_-mcpu_pwr9.out 2>transformsplus.bc.opts-S_-O3_-mcpu_pwr9.err
cd ${DIR26}/benchspec/CPU/723.llvm_r/run/run_base_refrate_${EXT26}.0000 &&  ./llvm-opt_r_base.${EXT26} codegen.bc -S -O3 -mcpu=pwr9 --sha512 -o codegen.bc.opts-S_-O3_-mcpu_pwr9.ll  1>codegen.bc.opts-S_-O3_-mcpu_pwr9.out 2>codegen.bc.opts-S_-O3_-mcpu_pwr9.err
cd ${DIR26}/benchspec/CPU/727.cppcheck_r/run/run_base_refrate_${EXT26}.0000 &&  ./cppcheck_r_base.${EXT26} --force 738-diamond-record.cpp --checkers-report=738_report.txt --enable=all --output-file=738_bogey.txt --platform=unix64  1>cppcheck_r.738_bogey.out 2>cppcheck_r.738_bogey.err
cd ${DIR26}/benchspec/CPU/727.cppcheck_r/run/run_base_refrate_${EXT26}.0000 &&  ./cppcheck_r_base.${EXT26} --force 747-dealii-data_out_base.cc --checkers-report=747_report.txt --enable=all --output-file=747_bogey.txt --platform=unix64  1>cppcheck_r.747_bogey.out 2>cppcheck_r.747_bogey.err
cd ${DIR26}/benchspec/CPU/727.cppcheck_r/run/run_base_refrate_${EXT26}.0000 &&  ./cppcheck_r_base.${EXT26} --force 770-7z-SystemPage.cpp --checkers-report=770_report.txt --output-file=770_bogey.txt --platform=unix64  1>cppcheck_r.770_bogey.out 2>cppcheck_r.770_bogey.err
cd ${DIR26}/benchspec/CPU/729.abc_r/run/run_base_refrate_${EXT26}.0000 &&  ./abc_r_base.${EXT26} -F twoexact.in  1>twoexact.out 2>twoexact.err
cd ${DIR26}/benchspec/CPU/729.abc_r/run/run_base_refrate_${EXT26}.0000 &&  ./abc_r_base.${EXT26} -F beem6-fraig.in  1>beem6-fraig.out 2>beem6-fraig.err
cd ${DIR26}/benchspec/CPU/729.abc_r/run/run_base_refrate_${EXT26}.0000 &&  ./abc_r_base.${EXT26} -F mem_ctrl.in  1>mem_ctrl.out 2>mem_ctrl.err
cd ${DIR26}/benchspec/CPU/729.abc_r/run/run_base_refrate_${EXT26}.0000 &&  ./abc_r_base.${EXT26} -F vga_lcd_miter.in  1>vga_lcd_miter.out 2>vga_lcd_miter.err
cd ${DIR26}/benchspec/CPU/729.abc_r/run/run_base_refrate_${EXT26}.0000 &&  ./abc_r_base.${EXT26} -F mcml.in  1>mcml.out 2>mcml.err
cd ${DIR26}/benchspec/CPU/729.abc_r/run/run_base_refrate_${EXT26}.0000 &&  ./abc_r_base.${EXT26} -F des_system90.in  1>des_system90.out 2>des_system90.err
cd ${DIR26}/benchspec/CPU/734.vpr_r/run/run_base_refrate_${EXT26}.0000 &&  ./vpr_base.${EXT26} stratixiv_arch.timing.xml JPEG_stratixiv_arch_timing.blif --RL_agent_placement off --place_algorithm bounding_box --max_criticality 0.0 --init_t 512 --alpha_t 0.75 --exit_t 1 --router_initial_timing all_critical --routing_failure_predictor off --route_chan_width 300 --max_router_iterations 20 --router_lookahead classic --initial_pres_fac 1.0 --pres_fac_mult 2.0 --astar_fac 1.5 --router_profiler_astar_fac 1.5 --seed 3 --sdc_file JPEG_stratixiv_arch_timing.sdc --pack_verbosity 0 --netlist_verbosity 0 --base_cost_type demand_only --inner_num 4 --read_initial_place_file ref_JPEG_stratixiv_arch_timing.init.place --place  1>JPEG_stratixiv_arch_timing.blif.place.out 2>JPEG_stratixiv_arch_timing.blif.place.err
cd ${DIR26}/benchspec/CPU/734.vpr_r/run/run_base_refrate_${EXT26}.0000 &&  ./vpr_base.${EXT26} stratixiv_arch.timing.xml JPEG_stratixiv_arch_timing.blif --place_algorithm bounding_box --place_static_notiming_move_prob 50 25 25 --max_criticality 0.0 --router_initial_timing all_critical --routing_failure_predictor off --route_chan_width 300 --max_router_iterations 20 --router_lookahead classic --initial_pres_fac 1.0 --pres_fac_mult 2.0 --astar_fac 1.5 --router_profiler_astar_fac 1.5 --seed 3 --sdc_file JPEG_stratixiv_arch_timing.sdc --pack_verbosity 0 --netlist_verbosity 0 --base_cost_type demand_only --place_file ref_JPEG_stratixiv_arch_timing.place --analysis --route  1>JPEG_stratixiv_arch_timing.blif.route.out 2>JPEG_stratixiv_arch_timing.blif.route.err
cd ${DIR26}/benchspec/CPU/734.vpr_r/run/run_base_refrate_${EXT26}.0000 &&  ./vpr_base.${EXT26} stratixiv_arch.timing.xml smithwaterman_stratixiv_arch_timing.blif --RL_agent_placement off --place_algorithm bounding_box --max_criticality 0.0 --init_t 512 --alpha_t 0.75 --exit_t 1 --router_initial_timing all_critical --routing_failure_predictor off --route_chan_width 300 --max_router_iterations 20 --router_lookahead classic --initial_pres_fac 1.0 --pres_fac_mult 2.0 --astar_fac 1.5 --router_profiler_astar_fac 1.5 --seed 3 --sdc_file smithwaterman_stratixiv_arch_timing.sdc --pack_verbosity 0 --netlist_verbosity 0 --base_cost_type demand_only --inner_num 1.8 --read_initial_place_file ref_smithwaterman_stratixiv_arch_timing.init.place --place  1>smithwaterman_stratixiv_arch_timing.blif.place.out 2>smithwaterman_stratixiv_arch_timing.blif.place.err
cd ${DIR26}/benchspec/CPU/734.vpr_r/run/run_base_refrate_${EXT26}.0000 &&  ./vpr_base.${EXT26} stratixiv_arch.timing.xml smithwaterman_stratixiv_arch_timing.blif --place_algorithm bounding_box --place_static_notiming_move_prob 50 25 25 --max_criticality 0.0 --router_initial_timing all_critical --routing_failure_predictor off --route_chan_width 300 --max_router_iterations 20 --router_lookahead classic --initial_pres_fac 1.0 --pres_fac_mult 2.0 --astar_fac 1.5 --router_profiler_astar_fac 1.5 --seed 3 --sdc_file smithwaterman_stratixiv_arch_timing.sdc --pack_verbosity 0 --netlist_verbosity 0 --base_cost_type demand_only --place_file ref_smithwaterman_stratixiv_arch_timing.place --analysis --route  1>smithwaterman_stratixiv_arch_timing.blif.route.out 2>smithwaterman_stratixiv_arch_timing.blif.route.err
cd ${DIR26}/benchspec/CPU/735.gem5_r/run/run_base_refrate_${EXT26}.0000 &&  ./gem5sim_base.${EXT26} --stats-file=run_riscv_boot.py_o3_10_--max-ticks_10_000_000_000.stats.txt run_riscv_boot.py o3 10 --max-ticks 10_000_000_000  1>run_riscv_boot.py_o3_10_--max-ticks_10_000_000_000.out 2>run_riscv_boot.py_o3_10_--max-ticks_10_000_000_000.err
cd ${DIR26}/benchspec/CPU/735.gem5_r/run/run_base_refrate_${EXT26}.0000 &&  ./gem5sim_base.${EXT26} --stats-file=run_riscv_boot.py_timing_4_--max-ticks_20_000_000_000.stats.txt run_riscv_boot.py timing 4 --max-ticks 20_000_000_000  1>run_riscv_boot.py_timing_4_--max-ticks_20_000_000_000.out 2>run_riscv_boot.py_timing_4_--max-ticks_20_000_000_000.err
cd ${DIR26}/benchspec/CPU/735.gem5_r/run/run_base_refrate_${EXT26}.0000 &&  ./gem5sim_base.${EXT26} --stats-file=synthetic_traffic.py_LinearGenerator_21.stats.txt synthetic_traffic.py LinearGenerator 21  1>synthetic_traffic.py_LinearGenerator_21.out 2>synthetic_traffic.py_LinearGenerator_21.err
cd ${DIR26}/benchspec/CPU/735.gem5_r/run/run_base_refrate_${EXT26}.0000 &&  ./gem5sim_base.${EXT26} --stats-file=synthetic_traffic.py_LinearGenerator_74_--ruby.stats.txt synthetic_traffic.py LinearGenerator 74 --ruby  1>synthetic_traffic.py_LinearGenerator_74_--ruby.out 2>synthetic_traffic.py_LinearGenerator_74_--ruby.err
cd ${DIR26}/benchspec/CPU/750.sealcrypto_r/run/run_base_refrate_${EXT26}.0000 &&  ./sealcrypto_r_base.${EXT26} refrate ecuador_province_capitals_refrate.csv Galapagos  1>homoencrypt.refrate_ecuador_province_capitals_refrate.csv_Galapagos.out 2>homoencrypt.refrate_ecuador_province_capitals_refrate.csv_Galapagos.err
cd ${DIR26}/benchspec/CPU/753.ns3_r/run/run_base_refrate_${EXT26}.0000 &&  ./ns3_r_base.${EXT26} mobile-scenario --simTimeMinutes=3 --RngSeed=1 --RngRun=1  1>mobile-scenario_0.out 2>mobile-scenario_0.err
cd ${DIR26}/benchspec/CPU/753.ns3_r/run/run_base_refrate_${EXT26}.0000 &&  ./ns3_r_base.${EXT26} tcp-pacing --simulationEndTime=500 --useEcn=false --RngSeed=1 --RngRun=1  1>tcp-pacing_1.out 2>tcp-pacing_1.err
cd ${DIR26}/benchspec/CPU/753.ns3_r/run/run_base_refrate_${EXT26}.0000 &&  ./ns3_r_base.${EXT26} lena-radio-link-failure --numberOfEnbs=2 --interSiteDistance=800 --simTime=200 --RngSeed=1 --RngRun=1  1>lena-radio-link-failure_2.out 2>lena-radio-link-failure_2.err
cd ${DIR26}/benchspec/CPU/753.ns3_r/run/run_base_refrate_${EXT26}.0000 &&  ./ns3_r_base.${EXT26} dctcp-example --enableSwitchEcn=true --flowStartupWindow=0.4 --convergenceTime=0.4 --measurementWindow=0.4 --RngSeed=1 --RngRun=1  1>dctcp-example_3.out 2>dctcp-example_3.err
cd ${DIR26}/benchspec/CPU/753.ns3_r/run/run_base_refrate_${EXT26}.0000 &&  ./ns3_r_base.${EXT26} wifi-mixed-network --isUdp=0 --payloadSize=3072 --simulationTime=25 --RngSeed=1 --RngRun=1  1>wifi-mixed-network_4.out 2>wifi-mixed-network_4.err
cd ${DIR26}/benchspec/CPU/753.ns3_r/run/run_base_refrate_${EXT26}.0000 &&  ./ns3_r_base.${EXT26} wifi-eht-network --simulationTime=0.2 --frequency=5 --useRts=1 --minExpectedThroughput=6 --maxExpectedThroughput=547 --RngSeed=1 --RngRun=1  1>wifi-eht-network_5.out 2>wifi-eht-network_5.err
cd ${DIR26}/benchspec/CPU/777.zstd_r/run/run_base_refrate_${EXT26}.0000 &&  ./zstd_base.${EXT26} -b3 -e3 --verbose -i40 cld.tar  1>zstd.b3_e3_verbose_i40_cld.tar.out 2>zstd.b3_e3_verbose_i40_cld.tar.err
cd ${DIR26}/benchspec/CPU/777.zstd_r/run/run_base_refrate_${EXT26}.0000 &&  ./zstd_base.${EXT26} -b5 -e5 --verbose -i25 cld.tar  1>zstd.b5_e5_verbose_i25_cld.tar.out 2>zstd.b5_e5_verbose_i25_cld.tar.err
cd ${DIR26}/benchspec/CPU/777.zstd_r/run/run_base_refrate_${EXT26}.0000 &&  ./zstd_base.${EXT26} -b7 -e7 --verbose -i12 cld.tar  1>zstd.b7_e7_verbose_i12_cld.tar.out 2>zstd.b7_e7_verbose_i12_cld.tar.err
cd ${DIR26}/benchspec/CPU/777.zstd_r/run/run_base_refrate_${EXT26}.0000 &&  ./zstd_base.${EXT26} -b10 -e10 --verbose -i6 cld.tar  1>zstd.b10_e10_verbose_i6_cld.tar.out 2>zstd.b10_e10_verbose_i6_cld.tar.err
cd ${DIR26}/benchspec/CPU/777.zstd_r/run/run_base_refrate_${EXT26}.0000 &&  ./zstd_base.${EXT26} -b14 -e14 --verbose -i4 cld.tar  1>zstd.b14_e14_verbose_i4_cld.tar.out 2>zstd.b14_e14_verbose_i4_cld.tar.err
cd ${DIR26}/benchspec/CPU/777.zstd_r/run/run_base_refrate_${EXT26}.0000 &&  ./zstd_base.${EXT26} -b16 -e16 --verbose -i1 cld.tar  1>zstd.b16_e16_verbose_i1_cld.tar.out 2>zstd.b16_e16_verbose_i1_cld.tar.err
cd ${DIR26}/benchspec/CPU/777.zstd_r/run/run_base_refrate_${EXT26}.0000 &&  ./zstd_base.${EXT26} -b18 -e18 --verbose -i1 cld.tar  1>zstd.b18_e18_verbose_i1_cld.tar.out 2>zstd.b18_e18_verbose_i1_cld.tar.err
cd ${DIR26}/benchspec/CPU/777.zstd_r/run/run_base_refrate_${EXT26}.0000 &&  ./zstd_base.${EXT26} -b19 -e19 --verbose -i1 cld.tar  1>zstd.b19_e19_verbose_i1_cld.tar.out 2>zstd.b19_e19_verbose_i1_cld.tar.err
cd ${DIR26}/benchspec/CPU/709.cactus_r/run/run_base_refrate_${EXT26}.0000 &&  ./cactus_base.${EXT26} ShiftedGaugeWave.par  1>cactus.out 2>cactus.err
cd ${DIR26}/benchspec/CPU/722.palm_r/run/run_base_refrate_${EXT26}.0000 &&  ./palm_r_base.${EXT26} <runfile_atmos 1>palm_r.out 2>palm_r.err
cd ${DIR26}/benchspec/CPU/731.astcenc_r/run/run_base_refrate_${EXT26}.0000 &&  ./astcenc_r_base.${EXT26} ref-inputs-linear.txt  1>astcenc_r.0.out 2>astcenc_r.0.err
cd ${DIR26}/benchspec/CPU/731.astcenc_r/run/run_base_refrate_${EXT26}.0000 &&  ./astcenc_r_base.${EXT26} ref-inputs-hdr.txt  1>astcenc_r.1.out 2>astcenc_r.1.err
cd ${DIR26}/benchspec/CPU/731.astcenc_r/run/run_base_refrate_${EXT26}.0000 &&  ./astcenc_r_base.${EXT26} ref-inputs-precision.txt  1>astcenc_r.2.out 2>astcenc_r.2.err
cd ${DIR26}/benchspec/CPU/736.ocio_r/run/run_base_refrate_${EXT26}.0000 &&  ./ocioperf_base.${EXT26} --spec-validation-offset 101 --spec-validation-stride 17 --spec-validation-pixels 131 --bitdepths ui16 ui16 --iter 100 --test -1 --transform ctf/lut1d_halfdom.ctf  1>perf_lut1d_halfdom.ctf.out 2>perf_lut1d_halfdom.ctf.err
cd ${DIR26}/benchspec/CPU/736.ocio_r/run/run_base_refrate_${EXT26}.0000 &&  ./ocioperf_base.${EXT26} --spec-validation-offset 202 --spec-validation-stride 19 --spec-validation-pixels 132 --bitdepths ui16 f32 --iter 200 --8kres --test 0 --transform ctf/mntr_srgb_identity.ctf  1>perf_mntr_srgb_identity.ctf.out 2>perf_mntr_srgb_identity.ctf.err
cd ${DIR26}/benchspec/CPU/736.ocio_r/run/run_base_refrate_${EXT26}.0000 &&  ./ocioperf_base.${EXT26} --spec-validation-offset 303 --spec-validation-stride 23 --spec-validation-pixels 133 --bitdepths f32 f32 --iter 20 --8kres --test -1 --transform clf/aces_to_video_with_look.clf  1>perf_aces_to_video_with_look.clf.out 2>perf_aces_to_video_with_look.clf.err
cd ${DIR26}/benchspec/CPU/736.ocio_r/run/run_base_refrate_${EXT26}.0000 &&  ./ocioperf_base.${EXT26} --spec-validation-offset 404 --spec-validation-stride 29 --spec-validation-pixels 134 --bitdepths f32 f32 --iter 25 --test -1 --transform clf/heavy_transform.clf  1>perf_heavy_transform.clf.out 2>perf_heavy_transform.clf.err
cd ${DIR26}/benchspec/CPU/737.gmsh_r/run/run_base_refrate_${EXT26}.0000 &&  ./gmsh_r_base.${EXT26} -option gmsh.opts -nt 0 choi.geo  1>choi.geo.out 2>choi.geo.err
cd ${DIR26}/benchspec/CPU/737.gmsh_r/run/run_base_refrate_${EXT26}.0000 &&  ./gmsh_r_base.${EXT26} -option gmsh.opts -nt 0 mediterranean.geo  1>mediterranean.geo.out 2>mediterranean.geo.err
cd ${DIR26}/benchspec/CPU/737.gmsh_r/run/run_base_refrate_${EXT26}.0000 &&  ./gmsh_r_base.${EXT26} -option gmsh.opts -nt 0 projection.geo  1>projection.geo.out 2>projection.geo.err
cd ${DIR26}/benchspec/CPU/737.gmsh_r/run/run_base_refrate_${EXT26}.0000 &&  ./gmsh_r_base.${EXT26} -option gmsh.opts -nt 0 gasdis.geo  1>gasdis.geo.out 2>gasdis.geo.err
cd ${DIR26}/benchspec/CPU/737.gmsh_r/run/run_base_refrate_${EXT26}.0000 &&  ./gmsh_r_base.${EXT26} -option gmsh.opts -nt 0 Torus.geo  1>Torus.geo.out 2>Torus.geo.err
cd ${DIR26}/benchspec/CPU/737.gmsh_r/run/run_base_refrate_${EXT26}.0000 &&  ./gmsh_r_base.${EXT26} -option gmsh.opts -nt 0 spec.geo -clscale 0.175 -algo del2d -algo hxt  1>spec.geo.out 2>spec.geo.err
cd ${DIR26}/benchspec/CPU/737.gmsh_r/run/run_base_refrate_${EXT26}.0000 &&  ./gmsh_r_base.${EXT26} -option gmsh.opts -nt 0 p19.geo  1>p19.geo.out 2>p19.geo.err
cd ${DIR26}/benchspec/CPU/748.flightdm_r/run/run_base_refrate_${EXT26}.0000 &&  ./JSBSim_base.${EXT26} --nohighlight scripts/weather-balloon2.xml  1>weather-balloon2.xml.out 2>weather-balloon2.xml.err
cd ${DIR26}/benchspec/CPU/748.flightdm_r/run/run_base_refrate_${EXT26}.0000 &&  ./JSBSim_base.${EXT26} --nohighlight scripts/B747_script1.xml  1>B747_script1.xml.out 2>B747_script1.xml.err
cd ${DIR26}/benchspec/CPU/748.flightdm_r/run/run_base_refrate_${EXT26}.0000 &&  ./JSBSim_base.${EXT26} --nohighlight scripts/x153.xml  1>x153.xml.out 2>x153.xml.err
cd ${DIR26}/benchspec/CPU/748.flightdm_r/run/run_base_refrate_${EXT26}.0000 &&  ./JSBSim_base.${EXT26} --nohighlight scripts/c3104.xml  1>c3104.xml.out 2>c3104.xml.err
cd ${DIR26}/benchspec/CPU/748.flightdm_r/run/run_base_refrate_${EXT26}.0000 &&  ./JSBSim_base.${EXT26} --nohighlight scripts/ah1s_flight_test.xml  1>ah1s_flight_test.xml.out 2>ah1s_flight_test.xml.err
cd ${DIR26}/benchspec/CPU/748.flightdm_r/run/run_base_refrate_${EXT26}.0000 &&  ./JSBSim_base.${EXT26} --nohighlight scripts/ball_orbit_g_torque.xml  1>ball_orbit_g_torque.xml.out 2>ball_orbit_g_torque.xml.err
cd ${DIR26}/benchspec/CPU/748.flightdm_r/run/run_base_refrate_${EXT26}.0000 &&  ./JSBSim_base.${EXT26} --nohighlight scripts/ball_orbit_g_torque2.xml  1>ball_orbit_g_torque2.xml.out 2>ball_orbit_g_torque2.xml.err
cd ${DIR26}/benchspec/CPU/748.flightdm_r/run/run_base_refrate_${EXT26}.0000 &&  ./JSBSim_base.${EXT26} --nohighlight scripts/ball_orbit.xml  1>ball_orbit.xml.out 2>ball_orbit.xml.err
cd ${DIR26}/benchspec/CPU/749.fotonik3d_r/run/run_base_refrate_${EXT26}.0000 &&  ./fotonik3d_r_base.${EXT26}  1>fotonik3d.log 2>fotonik3d.err
cd ${DIR26}/benchspec/CPU/765.roms_r/run/run_base_refrate_${EXT26}.0000 &&  ./roms_r_base.${EXT26} <roms_benchmark2.in.x 1>roms_benchmark2.log 2>roms_benchmark2.err
cd ${DIR26}/benchspec/CPU/766.femflow_r/run/run_base_refrate_${EXT26}.0000 &&  ./femflow_r_base.${EXT26} refrate.prm  1>femflow.out 2>femflow.err
cd ${DIR26}/benchspec/CPU/767.nest_r/run/run_base_refrate_${EXT26}.0000 &&  ./nest_r_base.${EXT26} cuba_stdp.sli  1>cuba_stdp.sli.out 2>cuba_stdp.sli.err
cd ${DIR26}/benchspec/CPU/767.nest_r/run/run_base_refrate_${EXT26}.0000 &&  ./nest_r_base.${EXT26} structural_plasticity_benchmark.sli  1>structural_plasticity_benchmark.sli.out 2>structural_plasticity_benchmark.sli.err
cd ${DIR26}/benchspec/CPU/767.nest_r/run/run_base_refrate_${EXT26}.0000 &&  ./nest_r_base.${EXT26} ArtificialSynchrony.sli  1>ArtificialSynchrony.sli.out 2>ArtificialSynchrony.sli.err
cd ${DIR26}/benchspec/CPU/772.marian_r/run/run_base_refrate_${EXT26}.0000 &&  ./marian-decoder_base.${EXT26} --cpu-threads 1 -m model.alphas.npz -v vocab.spm vocab.spm --beam-size 1 --mini-batch 32 --maxi-batch 100 --maxi-batch-sort src -w 512 --skip-cost --gemm-type intgemm8 --intgemm-options precomputed-alpha standard-only --quiet --quiet-translation -i TildeMODEL-spec.en --log TildeMODEL-spec.log --log-level off -o TildeMODEL-spec.out  1>run_TildeMODEL-spec.out.out 2>run_TildeMODEL-spec.out.err
cd ${DIR26}/benchspec/CPU/772.marian_r/run/run_base_refrate_${EXT26}.0000 &&  ./marian-decoder_base.${EXT26} --cpu-threads 1 -m model.alphas.npz -v vocab.spm vocab.spm --beam-size 1 --mini-batch 32 --maxi-batch 100 --maxi-batch-sort src -w 512 --skip-cost --gemm-type intgemm8 --intgemm-options precomputed-alpha standard-only --quiet --quiet-translation -i EuroPat-spec.en --log EuroPat-spec.log --log-level off -o EuroPat-spec.out  1>run_EuroPat-spec.out.out 2>run_EuroPat-spec.out.err
cd ${DIR26}/benchspec/CPU/782.lbm_r/run/run_base_refrate_${EXT26}.0000 &&  ./lbm_r_base.${EXT26} 900 reference.dat 0 0 200_200_130_ldc.of  1>lbm.out 2>lbm.err
