#!/bin/bash -x
# Source: https://github.com/rrwhx/runspec
DIR26=$(realpath .)
cd ${DIR26}/benchspec/CPU/706.stockfish_r/run/run_base_test_${EXT26}.0000 &&  ./stockfish_base.${EXT26} bench 16 1 15 spec_test.fen depth nnue  1>stockfish_spec_test_nnue.out 2>stockfish_spec_test_nnue.err
cd ${DIR26}/benchspec/CPU/706.stockfish_r/run/run_base_test_${EXT26}.0000 &&  ./stockfish_base.${EXT26} bench 16 1 15 spec_test.fen depth classical  1>stockfish_spec_test_classical.out 2>stockfish_spec_test_classical.err
cd ${DIR26}/benchspec/CPU/707.ntest_r/run/run_base_test_${EXT26}.0000 &&  ./ntest_r_base.${EXT26} OneGame.ggf 10 6  1>ntest.OneGame.10.6.out 2>ntest.OneGame.10.6.err
cd ${DIR26}/benchspec/CPU/708.sqlite_r/run/run_base_test_${EXT26}.0000 &&  ./sqlite_r_base.${EXT26} --memdb --size 10 --testset main --verify  1>sqlite_r.main.out 2>sqlite_r.main.err
cd ${DIR26}/benchspec/CPU/710.omnetpp_r/run/run_base_test_${EXT26}.0000 &&  ./omnetpp_r_base.${EXT26} -f randomMesh.ini -c General  1>omnetpp.General-0.out 2>omnetpp.General-0.err
cd ${DIR26}/benchspec/CPU/710.omnetpp_r/run/run_base_test_${EXT26}.0000 &&  ./omnetpp_r_base.${EXT26} -f queuenet.ini -c OneFifo  1>omnetpp.OneFifo-0.out 2>omnetpp.OneFifo-0.err
cd ${DIR26}/benchspec/CPU/710.omnetpp_r/run/run_base_test_${EXT26}.0000 &&  ./omnetpp_r_base.${EXT26} -f queuenet.ini -c AllocDealloc  1>omnetpp.AllocDealloc-0.out 2>omnetpp.AllocDealloc-0.err
cd ${DIR26}/benchspec/CPU/714.cpython_r/run/run_base_test_${EXT26}.0000 &&  ./cpython_r_base.${EXT26} -I -B coreml_pb.py -i 2 -d 20  1>cpython_r_0.out 2>cpython_r_0.err
cd ${DIR26}/benchspec/CPU/721.gcc_r/run/run_base_test_${EXT26}.0000 &&  ./cc1_r_base.${EXT26} t1.c -O3 -finline-limit=50000 -o t1.c.opts-O3_-finline-limit_50000.s  1>t1.c.opts-O3_-finline-limit_50000.out 2>t1.c.opts-O3_-finline-limit_50000.err
cd ${DIR26}/benchspec/CPU/723.llvm_r/run/run_base_test_${EXT26}.0000 &&  ./llvm-opt_r_base.${EXT26} test.ll -S -O3 -mcpu=pwr9 --sha512 -o test.ll.opts-S_-O3_-mcpu_pwr9.ll  1>test.ll.opts-S_-O3_-mcpu_pwr9.out 2>test.ll.opts-S_-O3_-mcpu_pwr9.err
cd ${DIR26}/benchspec/CPU/727.cppcheck_r/run/run_base_test_${EXT26}.0000 &&  ./testrunner_r_base.${EXT26}  1>testrunner_r.out 2>testrunner_r.err
cd ${DIR26}/benchspec/CPU/727.cppcheck_r/run/run_base_test_${EXT26}.0000 &&  ./cppcheck_r_base.${EXT26} --force hello.c --output-file=hello_bogey.txt --platform=unix64  1>cppcheck_r.hello_bogey.out 2>cppcheck_r.hello_bogey.err
cd ${DIR26}/benchspec/CPU/729.abc_r/run/run_base_test_${EXT26}.0000 &&  ./abc_r_base.${EXT26} -F truthtable.in  1>truthtable.out 2>truthtable.err
cd ${DIR26}/benchspec/CPU/729.abc_r/run/run_base_test_${EXT26}.0000 &&  ./abc_r_base.${EXT26} -F riscv.in  1>riscv.out 2>riscv.err
cd ${DIR26}/benchspec/CPU/734.vpr_r/run/run_base_test_${EXT26}.0000 &&  ./vpr_base.${EXT26} stratixiv_arch.timing.xml murax_stratixiv_arch_timing.blif --place_algorithm bounding_box --RL_agent_placement off --max_criticality 0.0 --init_t 512 --alpha_t 0.75 --exit_t 1 --router_initial_timing all_critical --routing_failure_predictor off --route_chan_width 300 --max_router_iterations 20 --router_lookahead classic --initial_pres_fac 1.0 --pres_fac_mult 2.0 --astar_fac 1.5 --router_profiler_astar_fac 1.5 --seed 3 --sdc_file murax_stratixiv_arch_timing.sdc --pack_verbosity 0 --netlist_verbosity 0 --base_cost_type demand_only --inner_num 4 --read_initial_place_file ref_murax_stratixiv_arch_timing.init.place --place  1>murax_stratixiv_arch_timing.blif.place.out 2>murax_stratixiv_arch_timing.blif.place.err
cd ${DIR26}/benchspec/CPU/734.vpr_r/run/run_base_test_${EXT26}.0000 &&  ./vpr_base.${EXT26} stratixiv_arch.timing.xml murax_stratixiv_arch_timing.blif --place_algorithm bounding_box --place_static_notiming_move_prob 50 25 25 --max_criticality 0.0 --router_initial_timing all_critical --routing_failure_predictor off --route_chan_width 300 --max_router_iterations 20 --router_lookahead classic --initial_pres_fac 1.0 --pres_fac_mult 2.0 --astar_fac 1.5 --router_profiler_astar_fac 1.5 --seed 3 --sdc_file murax_stratixiv_arch_timing.sdc --pack_verbosity 0 --netlist_verbosity 0 --place_file ref_murax_stratixiv_arch_timing.place --base_cost_type demand_only --analysis --route  1>murax_stratixiv_arch_timing.blif.route.out 2>murax_stratixiv_arch_timing.blif.route.err
cd ${DIR26}/benchspec/CPU/735.gem5_r/run/run_base_test_${EXT26}.0000 &&  ./gem5sim_base.${EXT26} --stats-file=synthetic_traffic.py_LinearGenerator_100.stats.txt synthetic_traffic.py LinearGenerator 100  1>synthetic_traffic.py_LinearGenerator_100.out 2>synthetic_traffic.py_LinearGenerator_100.err
cd ${DIR26}/benchspec/CPU/750.sealcrypto_r/run/run_base_test_${EXT26}.0000 &&  ./sealcrypto_r_base.${EXT26} test country_capital_test.csv Ecuador  1>homoencrypt.test_country_capital_test.csv_Ecuador.out 2>homoencrypt.test_country_capital_test.csv_Ecuador.err
cd ${DIR26}/benchspec/CPU/753.ns3_r/run/run_base_test_${EXT26}.0000 &&  ./ns3_r_base.${EXT26} tcp-pacing --isPacingEnabled=true --tracing=false --RngSeed=1 --RngRun=1  1>tcp-pacing_0.out 2>tcp-pacing_0.err
cd ${DIR26}/benchspec/CPU/753.ns3_r/run/run_base_test_${EXT26}.0000 &&  ./ns3_r_base.${EXT26} wifi-mixed-network --simulationTime=2 --RngSeed=1 --RngRun=1  1>wifi-mixed-network_1.out 2>wifi-mixed-network_1.err
cd ${DIR26}/benchspec/CPU/777.zstd_r/run/run_base_test_${EXT26}.0000 &&  ./zstd_base.${EXT26} -b3 --verbose -i1  1>zstd.b3_verbose_i1.out 2>zstd.b3_verbose_i1.err
cd ${DIR26}/benchspec/CPU/709.cactus_r/run/run_base_test_${EXT26}.0000 &&  ./cactus_base.${EXT26} ShiftedGaugeWave.par  1>cactus.out 2>cactus.err
cd ${DIR26}/benchspec/CPU/722.palm_r/run/run_base_test_${EXT26}.0000 &&  ./palm_r_base.${EXT26} <runfile_atmos 1>palm_r.out 2>palm_r.err
cd ${DIR26}/benchspec/CPU/731.astcenc_r/run/run_base_test_${EXT26}.0000 &&  ./astcenc_r_base.${EXT26} test-inputs.txt  1>astcenc_r.0.out 2>astcenc_r.0.err
cd ${DIR26}/benchspec/CPU/736.ocio_r/run/run_base_test_${EXT26}.0000 &&  ./ocioperf_base.${EXT26} --spec-validation-offset 2 --spec-validation-stride 50 --spec-validation-pixels 144 --iter 20 --test -1 --transform ctf/metadata.ctf  1>perf_metadata.ctf.out 2>perf_metadata.ctf.err
cd ${DIR26}/benchspec/CPU/737.gmsh_r/run/run_base_test_${EXT26}.0000 &&  ./gmsh_r_base.${EXT26} -option gmsh.opts -nt 0 spec.geo -smooth 0 -clscale .60  1>spec.geo.out 2>spec.geo.err
cd ${DIR26}/benchspec/CPU/748.flightdm_r/run/run_base_test_${EXT26}.0000 &&  ./JSBSim_base.${EXT26} --nohighlight scripts/c1722.xml  1>c1722.xml.out 2>c1722.xml.err
cd ${DIR26}/benchspec/CPU/748.flightdm_r/run/run_base_test_${EXT26}.0000 &&  ./JSBSim_base.${EXT26} --nohighlight scripts/J2461.xml  1>J2461.xml.out 2>J2461.xml.err
cd ${DIR26}/benchspec/CPU/749.fotonik3d_r/run/run_base_test_${EXT26}.0000 &&  ./fotonik3d_r_base.${EXT26}  1>fotonik3d.log 2>fotonik3d.err
cd ${DIR26}/benchspec/CPU/765.roms_r/run/run_base_test_${EXT26}.0000 &&  ./roms_r_base.${EXT26} <roms_benchmark0.in.x 1>roms_benchmark0.log 2>roms_benchmark0.err
cd ${DIR26}/benchspec/CPU/766.femflow_r/run/run_base_test_${EXT26}.0000 &&  ./femflow_r_base.${EXT26} test.prm  1>femflow.out 2>femflow.err
cd ${DIR26}/benchspec/CPU/767.nest_r/run/run_base_test_${EXT26}.0000 &&  ./nest_r_base.${EXT26} BrodyHopfield.sli  1>BrodyHopfield.sli.out 2>BrodyHopfield.sli.err
cd ${DIR26}/benchspec/CPU/767.nest_r/run/run_base_test_${EXT26}.0000 &&  ./nest_r_base.${EXT26} balancedneuron.sli  1>balancedneuron.sli.out 2>balancedneuron.sli.err
cd ${DIR26}/benchspec/CPU/772.marian_r/run/run_base_test_${EXT26}.0000 &&  ./marian-decoder_base.${EXT26} --cpu-threads 1 -m model.alphas.npz -v vocab.spm vocab.spm --beam-size 1 --mini-batch 32 --maxi-batch 100 --maxi-batch-sort src -w 64 --skip-cost --gemm-type intgemm8 --intgemm-options precomputed-alpha standard-only --quiet --quiet-translation -i TildeMODEL-test.en --log TildeMODEL-test.log --log-level off -o TildeMODEL-test.out  1>run_TildeMODEL-test.out.out 2>run_TildeMODEL-test.out.err
cd ${DIR26}/benchspec/CPU/782.lbm_r/run/run_base_test_${EXT26}.0000 &&  ./lbm_r_base.${EXT26} 10 reference.dat 0 0 200_200_130_ldc.of  1>lbm.out 2>lbm.err
